# Generated by Django 4.1.1 on 2022-09-29 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ca3858d3-2902-4320-9009-3766bb099265'), editable=False, primary_key=True, serialize=False),
        ),
    ]
